# Nom du workflow
name: Talk Weather
# Déclencheurs de l'action
on:
  push:
    branches:
      - main
  schedule: # Exécution toutes les 2 minutes
    - cron: '*/2 * * * *'

jobs:
  # Nom de la tâche
  ask-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the weather
        run: |
          wttr=$(curl https://wttr.in/Paris)
          prompt="resume la météo à paris à partir de la réponse suivante : $wttr"
          curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${{secrets.GEMINI_API_KEY}}" \ 
                  -H 'Content-Type:application/json' \
                  -X POST \
                  -d '{ "contents": [{"parts":[{"text": "'$prompt'"}]}] }'
